web_dashboard: false
projects:
- /Users/mh4gf/ghq/github.com/MH4GF/issync
- /Users/mh4gf/ghq/github.com/thehearableapp/hearable-app
- /Users/mh4gf/ghq/github.com/thehearableapp/hearable-app-worktree/for-survey-import-11
- /Users/mh4gf/ghq/github.com/thehearableapp/hearable-app-worktree/for-survey-import-2
- /Users/mh4gf/ghq/github.com/thehearableapp/hearable-survey
- /Users/mh4gf/ghq/github.com/thehearableapp/mapps-fs-parser
