[env]
GOBIN = "{{env.HOME}}/.local/bin"

[tools]
node = "24.20.0"
go = "1.26.1"
ruby = "4.0.5"
claude-code = "latest"
opencode = "latest"
python = "3.12"

[settings]
idiomatic_version_file_enable_tools = ["node"]
ruby.compile = false
go_set_goroot = false
